RootCollection/urls.py
from django.urls import path
from .views import tree_view

urlpatterns = [
    path('tree/', tree_view, name='tree_view'),
]

manageMyTree/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RootCollection.urls')),

]

RootCollection/models.py
from django.db import models


class Root(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Category(models.Model):
    root = models.ForeignKey(Root, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.root} - {self.name}"


class AnimalKind(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.category} - {self.name}"


class Animal(models.Model):
    kind = models.ForeignKey(AnimalKind, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.kind} - {self.name}"

RootCollection/views.py
from django.shortcuts import render
from .models import Animal, AnimalKind, Category, Root
from django.db.models import Prefetch


def tree_view(request):
    roots = Root.objects.prefetch_related(
        Prefetch('category_set__animalkind_set__animal_set', queryset=Animal.objects.select_related('kind__category__root'))
    ).all()

    context = {}
    context['roots'] = roots
    return render(request, "dashboard.html", context)

RootCollection/templates/dashboard.html
{% extends "base-dashboard.html" %}
{% load i18n %}
{% block secondary_menu %}
{% endblock secondary_menu %}
{% load static %}

{% block title %}
{% endblock %}



{% block content %}

<section class="container assess-list">
    <div class="container-fluid project-list">
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                <strong>
                                    Root name
                                </strong>
                                <div class=" col-md-2" style="float: right;">

                                    <button type="submit" class="btn btn-primary btn-round btn-block">New Root</button>
                                </div>
                            </h2>
                        </div>
                        <div class="body project_report">
                            <div class="table-responsive">
                                <table class="table m-b-0 table-hover">
                                    <thead>

                                    </thead>

                                    <tbody>

                                        <div data-role="main" class="ui-content">
                                            {% for root in roots %}
                                            <div data-role="collapsible">
                                              <h1>{{root.name}}</h1>
                                                {% for category in root.category_set.all %}
                                                <div data-role="collapsible">
                                                    <h1>{{ category.name }}</h1>
                                                        {% for animal_kind in category.animalkind_set.all %}
                                                        <div data-role="collapsible">
                                                            <h1>{{ animal_kind.name }}</h1>
                                                                {% for animal in animal_kind.animal_set.all %}
                                                                <div data-role="collapsible">
                                                                    <h1>{{ animal.name }}</h1>

                                                                </div>
                                                                {% endfor %}
                                                        </div>
                                                        {% endfor %}
                                                </div>
                                                {% endfor %}
                                            </div>
                                            {% endfor %}
                                        </div>

                                        </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</section>

{% endblock %}

{% block scripts %}

<script>
    function formatNumberWithCommas(number) {
     return number.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
   }
   var myNumberElements = document.querySelectorAll(".my-number");

    // Loop through all the elements and format their numbers
    for (var i = 0; i < myNumberElements.length; i++) {
    // Get the number from the HTML element
    var myNumber = parseInt(myNumberElements[i].innerText);

    // Format the number using the formatNumberWithCommas() function
    var formattedNumber = formatNumberWithCommas(myNumber);

    // Insert the formatted number back into the HTML element
    myNumberElements[i].innerText = formattedNumber;
    }
 </script>
{% endblock %}

templates/base-dashboard.html
{% load static %}
{% load i18n %}
{% with current_path=request.resolver_match.url_name %}
<!DOCTYPE html>
<html class="no-js " lang="LANGUAGE_CODE">
<head>

    {% include "includes/_base-head.html" %}{% block extra_css %}{% endblock extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    {% block extra_styles %}{% endblock %}

</head>

<body class="theme-purple {% if bidi %}rtl{% endif %}">
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="m-t-30"><img class="" src="{% static 'images/icons/310-logo.png' %}" width="48" height="48" alt=""></div>
            <p>{% trans "Please wait..." %}</p>        
        </div>
    </div>
    <div class="overlay"></div>

    <!-- Top Bar -->
    <nav class="top_navbar" style="background-image: linear-gradient( 
        53.25turn, #2D306A, 77%, #9C0E58);" >
        <div class="container">
            
            <div class="row clearfix">
                <div class="col-12">
                    <div class="navbar-logo">
                        <a href="javascript:void(0);" class="bars"></a>
                        <a class="navbar-brand" href="">
                            <img src="{% static 'images/icons/310-logo.png' %}" width="45" alt="">
                            <span class="m-l-10">{% trans "" %}</span>
                        </a>
                    </div>
                   
                </div>
            </div>        
        </div>
    </nav>
    
    <section class="content profile_page">
        <div class="container">
            <!-- Strart Breadcrumbs Section -->

            <!-- End Breadcrumbs Section -->
           
            <!-- Start Main Content Section -->
            <div class="row">
                    {% block content %} {% endblock %}
                    
            </div>
           
            
            <!-- End Main Content Section -->
        </div>
        
    </section>
    
    <script src="{% static 'assets/bundles/libscripts.bundle.js' %}"></script> <!-- Lib Scripts Plugin Js ( jquery.v3.2.1, Bootstrap4 js) --> 
    <script src="{% static 'assets/bundles/vendorscripts.bundle.js' %}"></script> <!-- slimscroll, waves Scripts Plugin Js -->

    <script src="{% static 'assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js' %}"></script> <!-- Bootstrap Colorpicker Js --> 
    <script src="{% static 'assets/plugins/jquery-inputmask/jquery.inputmask.bundle.js' %}"></script> <!-- Input Mask Plugin Js --> 
    <script src="{% static 'assets/plugins/multi-select/js/jquery.multi-select.js' %}"></script> <!-- Multi Select Plugin Js --> 
    <script src="{% static 'assets/plugins/jquery-spinner/js/jquery.spinner.js' %}"></script> <!-- Jquery Spinner Plugin Js --> 
    <script src="{% static 'assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js' %}"></script> <!-- Bootstrap Tags Input Plugin Js --> 
    <script src="{% static 'assets/plugins/nouislider/nouislider.js' %}"></script> <!-- noUISlider Plugin Js --> 
    <script src="{% static 'assets/plugins/sweetalert/sweetalert.min.js' %}"></script> <!-- noUISlider Plugin Js --> 
    <script src="{% static 'assets/plugins/bootstrap-notify/bootstrap-notify.js' %}"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="{% static 'assets/bundles/mainscripts.bundle.js' %}"></script>

    {% include "includes/_base-scripts.inc" %}
    {% block scripts %}{% endblock %}
</body>

</html>
{% endwith %}

templates/includes/_base-head.html
{% load static %}
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta
	content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
	name="viewport"
/>
<meta
	name="description"
	content="Responsive Bootstrap 4 and web Application ui kit."
/>
<title>310AI</title>
<link rel="icon" href="favicon.ico" type="image/x-icon" />
<!-- Favicon-->
<link
	rel="stylesheet"
	href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}"
/>
<link
	rel="stylesheet"
	href="{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.css' %}"
/>
<link
	rel="stylesheet"
	href="{% static 'assets/plugins/morrisjs/morris.min.css' %}"
/>
<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/jquery-steps/jquery.steps.css' %}" />
<!-- Morris Chart Css-->
<link rel="stylesheet" href="{% static 'assets/plugins/morrisjs/morris.css' %}" />
<!-- Colorpicker Css -->
<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.css' %}" />
<!-- Multi Select Css -->
<link rel="stylesheet" href="{% static 'assets/plugins/multi-select/css/multi-select.css' %}">
<!-- Bootstrap Spinner Css -->
<link rel="stylesheet" href="{% static 'assets/plugins/jquery-spinner/css/bootstrap-spinner.css' %}">
<!-- Bootstrap Tagsinput Css -->
<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css' %}">
<!-- Bootstrap Select Css -->
<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap-select/css/bootstrap-select.css' %}" />
<link rel="stylesheet" href="{% static 'assets/plugins/sweetalert/sweetalert.css' %}" />
<!-- noUISlider Css -->
<link rel="stylesheet" href="{% static 'assets/plugins/nouislider/nouislider.min.css' %}" />
<!-- Custom Css -->
<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
<link rel="stylesheet" href="{% static 'assets/css/color_skins.css' %}" />
<link rel="stylesheet" href="{% static 'assets/css/rtl.css' %}" />

<link
	rel="apple-touch-icon"
	sizes="180x180"
	href="{% static 'images/icons/310-logo.png' %}"
/>
<link
	rel="icon"
	sizes="32x32"
	href="{% static 'images/icons/310-logo.png' %}"
/>
<link
	rel="icon"
	type="image/png"
	sizes="16x16"
	href="{% static 'images/icons/310-logo.png' %}"
/>
<link rel="manifest" href="/site.webmanifest" />
<title>{% block title %} 310AI {% endblock title %}</title>
<!-- CSS -->
<!-- Add Material font (Roboto) and Material icon as needed -->
<link
	href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i|Roboto+Mono:300,400,700|Roboto+Slab:300,400,700"
	rel="stylesheet"
/>
<link
	href="https://fonts.googleapis.com/icon?family=Material+Icons"
	rel="stylesheet"
/>

<link
	rel="stylesheet"
	href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
	integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu"
	crossorigin="anonymous"
/>
<link
	rel="stylesheet"
	href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}"
/>
<link rel="stylesheet" href="{% static 'assets/css/custom.css' %}" />
<link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
<script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

templates/includes/_menu.html
{% load i18n %}
{% load static %}
{% with current_path=request.resolver_match.url_name %}

<aside id="leftsidebar" class="sidebar h_menu" style="background-image: linear-gradient( 
    53.25turn, #2D306A, 77%, #9C0E58);">
    <div class="container">
        <div class="row clearfix">
            <div class="col-12">
                <div class="menu">
                    <ul class="list">
                        <li class="header">MAIN</li>

                       
                    </ul>
                </div>
            </div>
        </div>
    </div> 
</aside>

<!-- Right Sidebar -->
<aside id="rightsidebar" class="right-sidebar">
    <div class="slim_scroll">
        <div class="card">
            <h6>Skins</h6>
            <ul class="choose-skin list-unstyled">
                <li data-theme="purple" class="active">
                    <div class="purple"></div>
                </li>                   
                <li data-theme="blue">
                    <div class="blue"></div>
                </li>
                <li data-theme="cyan">
                    <div class="cyan"></div>
                </li>
                <li data-theme="green">
                    <div class="green"></div>
                </li>
                <li data-theme="orange">
                    <div class="orange"></div>
                </li>
                <li data-theme="blush">
                    <div class="blush"></div>
                </li>
            </ul>
        </div>
        <div class="card theme-light-dark">
            <h6>Left Menu</h6>
            <button class="btn btn-default btn-block btn-round btn-simple t-light">Light</button>
            <button class="btn btn-default btn-block btn-round t-dark">Dark</button>
        </div> 
        <div class="card">
            <h6>General Settings</h6>
            <ul class="setting-list list-unstyled">
                <li>
                    <div class="checkbox">
                        <input id="checkbox1" type="checkbox">
                        <label for="checkbox1">Report Panel Usage</label>
                    </div>
                </li>
                <li>
                    <div class="checkbox">
                        <input id="checkbox2" type="checkbox" checked="">
                        <label for="checkbox2">Email Redirect</label>
                    </div>
                </li>
                <li>
                    <div class="checkbox">
                        <input id="checkbox3" type="checkbox" checked="">
                        <label for="checkbox3">Notifications</label>
                    </div>                        
                </li>
                <li>
                    <div class="checkbox">
                        <input id="checkbox4" type="checkbox" checked="">
                        <label for="checkbox4">Auto Updates</label>
                    </div>
                </li>
                <li>
                    <div class="checkbox">
                        <input id="checkbox5" type="checkbox" checked="">
                        <label for="checkbox5">Offline</label>
                    </div>
                </li>
                <li>
                    <div class="checkbox">
                        <input id="checkbox6" type="checkbox" checked="">
                        <label for="checkbox6">Location Permission</label>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</aside>
{% endwith %}